### ISSUE TITLE
q shortcut doesn't close location lists

### ISSUE THREAD

**Issue by cinaeco** [jordansissel/vim-ackmore#1]
Hi, not sure if I'm doing it wrong?
I have both the ack and ackmore plugins installed.
Now that I have ackmore, the default behaviour of <leader>a is to open with a location list.

Unfortunately, the quick close 'q' remap only works for quickfix windows, not location list windows.
If I go to the ack plugin and delete the remap of q, your remap then works, and it closes out of both qf's.
I had thought that since your remap is initialised as an autocommand, it should override the remap in ack, but it seems the other way around.
Is there something I'm missing?

**Comment by jordansissel** [comment]
I couldn't figure out a good way to make 'q' close the quickfix and also the location windows. If you find a work around, let me know :)

**Comment by cinaeco** [comment]
Sure thing. I shall certainly be trying.

**Comment by cinaeco** [comment]
The problem is that the Ack plugin declares the mappings at each run, so the only way I've found around it is to force ackmore's remapping after each call to Ack. Not the cleanest of ways.

The Ack plugin just really shouldn't be redeclaring remaps all the time.

Anyway, the change can be seen in my fork. I've opened a pull request in case you want it.
